---
title: "Article 1 ; Nerves that sense touch may play role in autism"
description: |
  A short description of the post.
author:
  - name: Verrart Sarah
    url:
      https://sarahverrart.github.io/SarahVerrart-SarahVerrart_blog/: {}
date: 11-05-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Description:

  - Source of the article : American Academy of Neurology
  Lien : https://www.sciencedaily.com/releases/2020/10/201014160516.htm
  
  - Publication date : October 14th 2020, Science Daily
  
  - Word count : 479 words
  
  
# Vocabulary 
  
 | Word from the text | Synonym/definition in English                                                              | French translation            |
|--------------------|--------------------------------------------------------------------------------------------|-------------------------------|
| unbearable         | that cannot be endured, suffered through, or tolerated                                     | insupportable                 |
| insight            | an understanding of relationships that sheds light on or helps solve a problem.            | éclairage, perspective        |
| to involve         | to include or use (something) as a necessary part, circumstance, condition, or end result: | impliquer                     |
| damage             | injury, harm, or destruction that reduces value                                            | blessures, dégâts             |
| heat               | the condition or quality of being hot                                                      | chaleur                       |
| while              | as long as, even though                                                                    | tandis que                    |
| range              | the limits between which something can change or vary                                      | gamme, étendue                |
| degenerated        | to fall below a normal or desirable level in physical, mental, or moral qualities          | dégradé                       |
| threshold          | the point at which something begins or ends to take effect                                 | seuil                         |
| whether or not     | no matter if, even if                                                                      | que... ou non                 |
| barefoot           | with bare feet                                                                             | pieds nus, déchaussés         |
| unaware            | not knowing about (something)                                                              | ignorants, inconscients       |
| scratched          | to damage or mark the surface of by scraping with something rough                          | griffer                       |
| bruised            | injured by striking or pressing, causing a discolored spot                                 | couvert de bleus, contusionné |
| beyond             | more than                                                                                  | en plus de, au-delà de        |
| distressing        | sharp or strong anxiety, pain, or sorrow                                                   | pénible, éprouvant            |

# Analysis about the study

## Researchers
- The study has been led by Sung-Tsang Hsieh, researcher of National Taiwan University Hospital in Taipei 

## Published in? when?
- Published in the October 14 2020, in the medical journal Neurology® of the American Academy of Neurology. 

## General topic
- Nerves that control our sense of touch, situated in the peripheral nervous system, may play a role in autism disorder
- It could help us understand the development of the disease
- It could relieves the most of people with autism, because as 70% of them present differences in their sensory perception, or distressing sensory symptoms

## Procedure/what was examined
- The study involved 32 autistic men who were compared to 27 men and women from a control group
- All the participants had to undergo a skin biopsy to analyse the state of the fibers in their nerves
- In addition, they had to go through a test with heat pulses applied on their skin - The autistic persons also had to complete questionnaires about their sensory symptoms. 

## Conclusions/discovery
- The results of the study showed that 53% of the people with autism had a level of nerve fiber density that was too low, while the control group's levels were in the normal range 
- It explains why autistic people could handle higher temperatures than the other group, or being scratched or bruised without realizing it. 
- It teaches us that the response to touch of autistic people depends on the damage in their nerve fibers

## Remaining questions
- However, the study only involves 59 people, and all the autistic people were men. More investigations must be done to enable researchers to find a treatment of the distressing sensory symptoms.  
